ALTER TYPE "IngredientUnit" ADD VALUE IF NOT EXISTS 'PACKAGE';
ALTER TYPE "IngredientUnit" ADD VALUE IF NOT EXISTS 'DOZEN';
ALTER TYPE "IngredientUnit" ADD VALUE IF NOT EXISTS 'BOX';
ALTER TYPE "IngredientUnit" ADD VALUE IF NOT EXISTS 'LB';
